### ISSUE TITLE
NameError: name 'CrawlerProcess' is not defined

### ISSUE THREAD

**Issue by merval** [simon987/od-database#1]
Started crawling task
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dwalker/od-database/task.py", line 48, in execute_task
    process = CrawlerProcess(get_project_settings())
NameError: name 'CrawlerProcess' is not defined

**Comment by simon987** [comment]
Yes that's my fault, I forgot do make a branch and I'm slowly rewriting pretty much the whole project so it's broken right now.
It should work up to f1e8183cdf4ee1c3960e89beadc3f8ae804d1ce0.

If you were interested in contributing let me know I'll figure something out
